name: Python Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions for writing to pull requests and contents
permissions:
  pull-requests: write
  contents: write

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'poetry'
    
    - name: Install Dependencies
      run: poetry install --with dev
    
    - name: Run MyPy
      run: poetry run mypy --explicit-package-bases . --exclude venv
    
    - id: black-check
      name: Check Black formatting
      continue-on-error: true
      run: poetry run black --check .
    
    - name: Fix Black formatting issues
      if: steps.black-check.outcome == 'failure'
      run: poetry run black .
    
    - name: Commit formatting changes
      if: steps.black-check.outcome == 'failure'
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Fix formatting with Black'
        default_author: github_actions
        add: '.'
    
    - name: Run Pytest
      run: poetry run pytest tests
